### ISSUE TITLE
Clean Up Repo

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/gene-normalization#84]
- [x] Better documentation
    - [x] Add type hints 
- [ ] DRY
- [x] Remove unused code 
~- [ ] Rather than using vrs-python's VRS models, use ga4gh.vrsatile.pydantic models in `gene.vrs_locations`~
- [x] Check if we can remove `EBSampleApp-Python.iml`?
- [x] Add flake8-annotations + double quotes
- [x] String enums in schemas

**Comment by korikuzma** [comment]
I'm going to close this in favor of created more specific issues.
